name = "ExaPF"
uuid = "0cf0e50c-a82e-488f-ac7e-41ffdff1b8aa"
version = "0.12.0"
authors = ["Adrian Maldonado <maldonadod@anl.gov>", "Michel Schanen <mschanen@anl.gov>", "Fran√ßois Pacaud <fpacaud@anl.gov>", "Alexis Montoison <amontoison@anl.gov>"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDSS = "45b445bb-4962-46a0-9369-b4df9d0f772e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KLU = "ef3ab10e-7fda-4108-b977-705223b18434"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
KrylovPreconditioners = "45d422c2-293f-44ce-8315-2cb988662dec"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatrixColorings = "0a514795-09f3-496d-8182-132a7b665d35"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"

[extensions]
ExaPFAMDGPUExt = "AMDGPU"
ExaPFCUDAExt = "CUDA"

[compat]
AMDGPU = "2.0"
Adapt = "4.3"
ForwardDiff = "1.0"
GPUArraysCore = "0.2.0"
KLU = "0.6"
KernelAbstractions = "0.9"
Krylov = "0.10"
LazyArtifacts = "1.10"
LinearAlgebra = "1.10"
Printf = "1.10"
SparseArrays = "1.10"
SparseMatrixColorings = "0.4.18"
julia = "1.10"
