name = "ExaPF"
uuid = "0cf0e50c-a82e-488f-ac7e-41ffdff1b8aa"
authors = ["Adrian Maldonado <maldonadod@anl.gov>", "Michel Schanen <mschanen@anl.gov>", "Fran√ßois Pacaud <fpacaud@anl.gov>"]
version = "0.5.0"

[deps]
BlockPowerFlow = "0ca6dcf5-c23f-4097-a3ba-dae6c919a0c0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDAKernels = "72cfdca4-0801-4ab0-bf6a-d52aa10adc57"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
CUDA = "~2.3, 3.0"
FiniteDiff = "2.7"
ForwardDiff = "0.10"
KernelAbstractions = "0.6"
Krylov = "~0.6.0"
LightGraphs = "1.3"
MathOptInterface = "0.9"
Metis = "1"
SparseDiffTools = "1"
TimerOutputs = "0.5"
julia = "^1.5"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDAKernels = "72cfdca4-0801-4ab0-bf6a-d52aa10adc57"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[targets]
scripts = ["Ipopt", "NLsolve", "UnicodePlots", "BenchmarkTools"]
test = ["CUDAKernels", "Test", "Random", "Ipopt", "BenchmarkTools"]
