authors = ["Adrian Maldonado <maldonadod@anl.gov>", "Michel Schanen <mschanen@anl.gov>", "Fran√ßois Pacaud <fpacaud@anl.gov>"]
name = "ExaPF"
uuid = "0cf0e50c-a82e-488f-ac7e-41ffdff1b8aa"
version = "0.9.1"

[compat]
CUDA = "4.1, 5"
ForwardDiff = "0.10"
KernelAbstractions = "0.9"
Krylov = "0.9"
LightGraphs = "1.3"
Metis = "1"
SparseDiffTools = "1"
julia = "1.8"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
