name = "ExaPFApp"
uuid = "aa457b0c-507e-42d5-98f7-a9bb415058c8"
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDSS = "45b445bb-4962-46a0-9369-b4df9d0f772e"
ExaPF = "0cf0e50c-a82e-488f-ac7e-41ffdff1b8aa"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[compat]
CUDA = "5.9.5"
CUDSS = "0.6.4"
