[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDSS = "45b445bb-4962-46a0-9369-b4df9d0f772e"
CUSOLVERRF = "a8cc9031-bad2-4722-94f5-40deabb4245c"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ExaPF = "0cf0e50c-a82e-488f-ac7e-41ffdff1b8aa"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
KrylovPreconditioners = "45d422c2-293f-44ce-8315-2cb988662dec"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
